name: Test Runner
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - run: |
          haxe -version
          haxelib install heaps
          haxelib install heaps-aseprite
          haxelib install utest
          haxelib install haxe-doctest

      - name: "Run tests"
        run: haxe tests.hxml

