name: Test Runner
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  haxe-libs: heaps heaps-aseprite utest hashlink

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - run: |
          haxe -version
          haxelib install ${{ env.haxe-libs }}

      - name: "Run tests"
        run: haxe tests.hxml

