name: Test Runner
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Test with Haxe
      uses: vegardit/haxe-reusable-workflows/.github/workflows/test-with-haxe.yml@v1
      strategy:
        fail-fast: false
      with:
        haxe-version: '4.2.5'
        haxe-libs: heaps heaps-aseprite utest hashlink
        test-node: true
